---
- name: Install necessary packages
  gather_facts: yes
  hosts: streamer
  become: true

  vars_files:
    - vars/generic.yaml

  tasks:
  - name: Install libnginx-mod-rtmp and ffmpeg
    ansible.builtin.apt:
      update_cache: yes
      pkg:
        - nginx
        - libnginx-mod-rtmp
        - ffmpeg
      state: present

  - name: Deploy Nginx general configuration
    template:
      src: templates/streamer-nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: '0644'
    notify:
      - restart nginx

  - name: deploy new site configuration
    ansible.builtin.template:
      src: templates/streamer-hls.conf.j2
      dest: /etc/nginx/sites-enabled/streamer
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx


  - name: Copy FFmpeg script
    ansible.builtin.copy:
      src: files/ffmpeg.sh
      dest: /usr/local/bin/ffmpeg.sh
      mode: '0755'
    become: true

  - name: Download a video file
    get_url:
      url: https://www.pexels.com/download/video/20576968/
      dest: ~/video.mp4

  - name: Start FFmpeg for transcoding
    shell: /usr/local/bin/ffmpeg.sh
    async: 600
    poll: 0
    ignore_errors: yes
    become: true

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
