- name: Deploy devops website
  gather_facts: yes                         
  hosts: webservers                  
  
  vars_files:
    - vars/generic.yaml
  
  tasks:  
  - name: change index.html
    ansible.builtin.template:
      src: templates/index.html.j2
      dest: /var/www/{{domain}}/index.html
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    become: true
